Support File drag and drop
Tewr/BlazorFileReader pull request #49
Opened 2019-07-18 20:38 UTC by catlan

* Generalize HTMLInputElement.files and DragEvent.dataTransfer.files access
* Register drop event and fake drag end event

Sample:

```
<div id="dropTarget" @ref="@dropTargetlement" @ondrop="@(e => OnDrop(e))" ></div>

@code {
    ElementRef  dropTargetlement;
    IFileReaderRef fileReaderReference;

    protected override void OnAfterRender()
    {
        if (fileReaderReference == null)
        {
            fileReaderReference = fileReaderService.CreateOnDropReference(dropTargetlement);
        }
    }
    
    async Task OnDrop(UIDragEventArgs e)
    {
        foreach (var file in await fileReaderReference.EnumerateFilesAsync())
        {
            // Read into memory and act
            using(MemoryStream memoryStream = await file.CreateMemoryStreamAsync(4096)) {
                // Sync calls are ok once file is in memory
                memoryStream.Read(buffer, ...)
            }
        }
    }
}

```

2019-07-19 12:55 UTC, Tewr commented
Hello! Thank you for this. Conceptually I like it. I thought the API this was feature complete but this looks like some nice core functionality. Might be slippery to put it in a seperate assembly, so even though I'm not super familiar with the drag and drop api I'm really positive to the idea. 

I'll review it shortly but I can already say that in general it's fine. I'm just not at ease with the new method on `IFileReaderService` nor the way it is being initialized in the `FileReaderRef `constructor. 

Keep `IFileReaderService` and the  `FileReaderRef ` constructor the way it was.

Expose your method `Task InitializeAsync()` in `IFileReaderRef ` instead. 

But rename it to something better, how about  `Task RegisterDropAsync()` ?

So in your example it would be 

   ```
 protected override async Task OnAfterRenderAsync ()
    {
        if (fileReaderReference == null)
        {
            fileReaderReference = fileReaderService.CreateReference(dropTargetlement);
            await fileReaderReference.RegisterDropAsync();
        }
    }
```

2019-07-19 13:02 UTC, Tewr requested changes

2019-07-19 13:02 UTC, Tewr commented on src/Blazor.FileReader/script/FileReaderComponent.ts
> +        if (element instanceof HTMLInputElement) {
This code is copy-pasted in `GetFileInfoFromElement ` and `OpenRead`, Create a new private method (`GetFiles`?)

2019-07-19 13:02 UTC, Tewr commented on src/Blazor.FileReader/FileReaderRef.cs
> +        private async Task InitializeAsync()
Expose this in the interface and rename it

2019-07-19 13:02 UTC, Tewr commented on src/Blazor.FileReader/FileReaderRef.cs
> +                Initialization = InitializeAsync();
Remove from constructor

2019-07-19 13:02 UTC, Tewr commented on src/Blazor.FileReader/FileReaderService.cs
> +        public IFileReaderRef CreateOnDropReference(ElementRef dropElement)
Remove this method

2019-07-19 13:02 UTC, Tewr commented on src/Blazor.FileReader/FileReaderService.cs
> +        IFileReaderRef CreateOnDropReference(ElementRef dropElement);
Remove this method

2019-07-20 07:18 UTC, catlan commented
Thank you for your feedback. I'm also glade to get rid of the initializer part.

2019-07-21 13:33 UTC, Tewr approved these changes

2019-07-21 13:38 UTC, Tewr commented
I'm happy about the unregister part, the cherry on the cream. Many thanks. I'll make a new release as soon as I get the chance to test this,  probably in a few days.

I wonder if there is a way to create an E2e test with selenium for file drag and drop? Feels complicated. Time will tell...

2019-07-21 13:38 UTC, merged